services:
  gpt4free:
    image: hlohaus789/g4f:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3001
    environment:
      - OLLAMA_HOST=host.docker.internal
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
